export const textColour = '#49516B'
export const textLight = '#B6B9C4'
export const borderColour = '#DFDFDF'
export const borderLight = '#ECEDF0'
export const bgColour = '#F9F9F9'

export const offWhite = '#F2F3F5'

export const blue = '#68D1FB'
export const purple = '#782FF2'

export const black = '#000'
export const offBlack = '#343434'
export const white = '#fff'
export const grayBg = '#fafafa'
export const gray = '#55585B'
export const yellow = '#ffd200'
export const red = '#fc5f63'
export const netgearPurple = '#6d1a85'
export const voxeetBlue = '#4280c5'
export const waggleRed = '#f84242'
export const moodjiBlue = '#0ab5de'
export const quoteRobotBlue = '#25c5cc'
export const postachioGreen = '#37cca2'
export const volleyBlue = '#204068'
export const dataWalletRed = '#e0463e'
export const contractorsRed = '#ee4950'
export const gitlanceGray = '#eee'
export const kuperBlue = '#051c3e'
export const dubyBlue = '#43a3aa'
export const usedPurple = '#7243b6'
export const ftsGreen = '#77bd43'
export const posirankBlue = '#247ac5'
export const uboraBlue = '#004687'
export const roomchatGreen = '#7fca6d'

export const hr = '#eeeeee'
export const lightGray = '#ececec'
export const medGray = '#a3a3a3'
export const text = '#000'
